### ISSUE TITLE
Gradle 9.0 から非互換となるような deprecated な Gradle の機能が使用されている依存関係を更新する

### ISSUE THREAD

**Issue by private-yusuke** [twin-te/twinte-android#36]
# 概要

https://github.com/twin-te/twinte-android/actions/runs/4901944672/jobs/8753500168?pr=35#step:4:160 のように、動作が非互換となるような機能が利用されている旨が表示されることがある。

## 原因

https://github.com/twin-te/twinte-android/commit/e862e5d703bc6d2b145291be17738ad63ce0715d 時点で `./gradlew --stacktrace --warning-mode all assembleDebug` を実行すると、以下のような出力が得られる。

```
The AbstractCompile.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 9.0. Please use the destinationDirectory property instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.0/userguide/upgrading_version_7.html#compile_task_wiring
        at org.gradle.api.tasks.compile.AbstractCompile.getDestinationDir(AbstractCompile.java:90)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated.getDestinationDir(Unknown Source)
        at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler$wireKotlinTasks$preJavaKotlinOutput$1.call(Android25ProjectHandler.kt:52)
        at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler$wireKotlinTasks$preJavaKotlinOutput$1.call(Android25ProjectHandler.kt:50)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
        （以下略）
```

このログより、以下の行が原因となっていることがわかる。
https://github.com/twin-te/twinte-android/blob/a6380ee8ee5e324b66cb6f85a9e43000d7f47dcf/build.gradle.kts#L10

この依存関係は以下の `kotlinVersion` という変数に依存している。
https://github.com/twin-te/twinte-android/blob/a6380ee8ee5e324b66cb6f85a9e43000d7f47dcf/build.gradle.kts#L3

##  解決方法

#30 を実施する前に依存関係のバージョンをガッと上げるタイミングで Kotlin のバージョンも上げることになり、そのタイミングで同時に解決されることが期待される。

**Comment by private-yusuke** [comment]
#41 によって Kotlin のバージョンが上がり、`./gradlew --stacktrace --warning-mode all assembleDebug` でスタックトレースが表示されることはなくなった。
